### ISSUE TITLE
running DB sync with Docker can use all Linux Inodes 

### ISSUE THREAD

**Issue by HugoP27** [MerginMaps/mergin-db-sync#52]
/var/lib/docker/overlay2/_$long-string$_/diff/tmp/dbsyc/.mergin/work-packages directory is not cleaned in docker container and can easily reach up to a million+ diff files which uses up inodes on Linux, so although I have, for example, 100GiB ssd space of which only 33% is used, I only have 3.7 million inodes of which 90% are used by mergin-db-sync docker containers which stops the Linux machine from working. a good fix would be to delete previous diff's when a new one is downloaded

**Comment by wonder-sk** [comment]
It looks like the underlying issue is in mergin python client - https://github.com/lutraconsulting/mergin-py-client/issues/47 - and when used in mergin-db-sync for a longer time, the directory just grows and grows...
