### ISSUE TITLE
Add an option to notify admin when sync breaks

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mergin-db-sync#56]
It would be useful if the daemon would somehow notify admin when things go wrong (e.g. database schema has changed, unable to access project) - currently it just silently stops.

Maybe sending an email to the admin would help - or send a notification to slack...

**Comment by HugoP27** [comment]
We've added email notifications to our Lutra stack (db-sync and WP's) and it works great for notifying us when things go wrong. would be great if a user could specify email addresses in the config.ini file to receive error notifications

**Comment by saberraz** [comment]
It would be good to receive a notification indicating the name of the project that interrupts synchronisation & work of the db-sync container? Or perhaps it is possible for the notification to include a note about the nature of the error (e.g. schema changed for X project, deletion of containers already in progress, or not enough free space on disk) or sending log file?
