### ISSUE TITLE
Document how to restart failed sync

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mergin-db-sync#57]
Sometimes users modify structure of their database and this naturally breaks db-sync. It would be good to document how to restart db-sync when this happens.

If the "source" is a geopackage in Mergin project (where the database structure change happened), this boils down to these steps:
1. delete "base" and "main" schemas in PostgreSQL
2. start mergin-db-sync again with `--init-from-gkpg`

If the source is PostgreSQL:
1. delete "base" schema in PostgreSQL and the geopackage in the Mergin project
2. start mergin-db-sync again with `--init-from-db`

**Comment by timlinux** [comment]
Yeah that would work for me except dropping the main schema may have some nasty side effects if the user has skip tables etc.

**Comment by wonder-sk** [comment]
Related ticket to automate this: #16

**Comment by wonder-sk** [comment]
`--force-init` option has been added in #107 to do the cleanup after failed sync.
