### ISSUE TITLE
support multiple GPKG files

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/mergin-db-sync#61]
we recommend have 1 GPKG file for each QGIS layer (due to better conflict resolution). But to have multiple GPKG with db-sync, we need for each GPKG separate PG schema and also separate sync process.

**Comment by u-cav** [comment]
What is the correct procedure for syncing multiple GPKG files?

Is it necessary to create 2 schemas, and a sync block in the config for every GPKG?

**Comment by wonder-sk** [comment]
@u-cav yes indeed - for two GPKG files you need two different database schemas and therefore also two "connections" entries in db-sync configuration.

**Comment by u-cav** [comment]
@wonder-sk Perfect, thank you for the reply.

**Comment by holgerbermeo** [comment]
Could I synchronize several gpkg in a single scheme?

**Comment by holgerbermeo** [comment]
> @u-cav yes indeed - for two GPKG files you need two different database schemas and therefore also two "connections" entries in db-sync configuration.

Could I synchronize several gpkg in a single scheme?

**Comment by wonder-sk** [comment]
> Could I synchronize several gpkg in a single scheme?

@holgerbermeo no, sorry, each gpkg needs to be in a separate schema. You could simply just merge tables from multiple geopackages to a single gpkg...
