### ISSUE TITLE
Failure to connect to database

### ISSUE THREAD

**Issue by Ojaybee** [MerginMaps/mergin-db-sync#71]
I'm trying to run mergin-db-sync with Docker. I'm getting errors from the suggested command in the readme. 

When I use -e MERGIN__USERNAME=myUsername (double underscore) My Mergin username appears as 'None' and I'm asked for my Mergin password. Using a single underscore for MERGIN_USERNAME and MERGIN_PASSWORD the login to Mergin appears to work. However, I then receive the following error:

```
Connecting to the database...
Traceback (most recent call last):
  File "dbsync_daemon.py", line 65, in <module>
    main()
  File "dbsync_daemon.py", line 35, in main
    dbsync.dbsync_init(mc, from_gpkg=True)
  File "/mergin-db-sync/dbsync.py", line 507, in dbsync_init
    conn = psycopg2.connect(config.db_conn_info)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 123, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters
```
I can connect to this database using the same credentials without a problem through QGIS. 

**Update**
I now have an instance of mergin-db-sync running but the only way I found to do this was by manually editing the config.ini file in the container.

**Comment by wonder-sk** [comment]
@Ojaybee please try again - for a couple of days recently we had an inconsistency between what README said and what the latest Docker container expected. That should be fixed now...

**Comment by Ojaybee** [comment]
Yes that is fixed now. Thankyou!
