### ISSUE TITLE
GEODIFF Stuck at make

### ISSUE THREAD

**Issue by maharshirajbhandari** [MerginMaps/mergin-db-sync#87]
I'm stuck on the make part of step number 4 as explained in the installation instructions. The error log is attached.
![2023-01-19 17_18_34-root@innovative-vm-ec__home_mergin_geodiff_build](https://user-images.githubusercontent.com/65963815/213432810-d3d7ca23-52c7-49cd-b166-9658712b8274.png)

**Comment by PeterPetrik** [comment]
Hi @maharshirajbhandari , which OS do you use? You need to use sqlite3 with extensions allowed.
