### ISSUE TITLE
Write output to standard error stream

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mergin-db-sync#91]
Right now most of the messages from db-sync use print() so they go to stdout - but ideally they should go to stderr, so that then things work when e.g. using `docker logs` to get information about what's going on in the container.

**Comment by stevenjh** [comment]
Yep, agree, I'm using in Azure Container instances and the print logs are lost. I've updated media_sync to use the `logging` libary, then can swap prints for 
```
logging.error(f"Failed to upload {file['path']}: " + str(e))
logging.info("Updating references ...")
```

And added a `debug_level: 20` to the top level of config based on [these codes](https://docs.python.org/3/library/logging.html#levels)

Intending to pull request through with these changes, but I've got my repo muddled up with local logins etc
